create table if not exists refresh
 (
    token_id bigint generated by default as identity primary key not null,
    token varchar not null,
    expired_date timestamp not null,
    user_id bigint not null
);
